language: go

install: true

go_import_path: github.com/wallix/awless

go:
  - 1.11.x
  - 1.12.x

before_install:
  - go get github.com/mattn/goveralls
script:
  - $GOPATH/bin/goveralls -v -service=travis-ci
