package aws

import "github.com/wallix/awless/graph"

var awsResourcesDef = map[graph.ResourceType]map[string]*propertyTransform{
	graph.Instance: {
		"Id":             {name: "InstanceId", transform: extractValueFn},
		"Name":           {name: "Tags", transform: extractTagFn("Name")},
		"Type":           {name: "InstanceType", transform: extractValueFn},
		"SubnetId":       {name: "SubnetId", transform: extractValueFn},
		"VpcId":          {name: "VpcId", transform: extractValueFn},
		"PublicIp":       {name: "PublicIpAddress", transform: extractValueFn},
		"PrivateIp":      {name: "PrivateIpAddress", transform: extractValueFn},
		"ImageId":        {name: "ImageId", transform: extractValueFn},
		"LaunchTime":     {name: "LaunchTime", transform: extractValueFn},
		"State":          {name: "State", transform: extractFieldFn("Name")},
		"KeyName":        {name: "KeyName", transform: extractValueFn},
		"SecurityGroups": {name: "SecurityGroups", transform: extractSliceValues("GroupId")},
	},
	graph.Vpc: {
		"Id":        {name: "VpcId", transform: extractValueFn},
		"Name":      {name: "Tags", transform: extractTagFn("Name")},
		"IsDefault": {name: "IsDefault", transform: extractValueFn},
		"State":     {name: "State", transform: extractValueFn},
		"CidrBlock": {name: "CidrBlock", transform: extractValueFn},
	},
	graph.Subnet: {
		"Id":                  {name: "SubnetId", transform: extractValueFn},
		"Name":                {name: "Tags", transform: extractTagFn("Name")},
		"VpcId":               {name: "VpcId", transform: extractValueFn},
		"MapPublicIpOnLaunch": {name: "MapPublicIpOnLaunch", transform: extractValueFn},
		"State":               {name: "State", transform: extractValueFn},
		"CidrBlock":           {name: "CidrBlock", transform: extractValueFn},
		"AvailabilityZone":    {name: "AvailabilityZone", transform: extractValueFn},
		"DefaultForAz":        {name: "DefaultForAz", transform: extractValueFn},
	},
	graph.SecurityGroup: {
		"Id":            {name: "GroupId", transform: extractValueFn},
		"Name":          {name: "GroupName", transform: extractValueFn},
		"Description":   {name: "Description", transform: extractValueFn},
		"InboundRules":  {name: "IpPermissions", transform: extractIpPermissionSliceFn},
		"OutboundRules": {name: "IpPermissionsEgress", transform: extractIpPermissionSliceFn},
		"OwnerId":       {name: "OwnerId", transform: extractValueFn},
		"VpcId":         {name: "VpcId", transform: extractValueFn},
	},
	graph.Keypair: {
		"Id":             {name: "KeyName", transform: extractValueFn},
		"Name":           {name: "KeyName", transform: extractValueFn},
		"KeyFingerprint": {name: "KeyFingerprint", transform: extractValueFn},
	},
	graph.Volume: {
		"Id":               {name: "VolumeId", transform: extractValueFn},
		"Name":             {name: "Tags", transform: extractTagFn("Name")},
		"VolumeType":       {name: "VolumeType", transform: extractValueFn},
		"State":            {name: "State", transform: extractValueFn},
		"Size":             {name: "Size", transform: extractValueFn},
		"Encrypted":        {name: "Encrypted", transform: extractValueFn},
		"CreateTime":       {name: "CreateTime", transform: extractValueFn},
		"AvailabilityZone": {name: "AvailabilityZone", transform: extractValueFn},
	},
	graph.User: {
		"Id":                   {name: "UserId", transform: extractValueFn},
		"Name":                 {name: "UserName", transform: extractValueFn},
		"Arn":                  {name: "Arn", transform: extractValueFn},
		"Path":                 {name: "Path", transform: extractValueFn},
		"CreateDate":           {name: "CreateDate", transform: extractValueFn},
		"PasswordLastUsedDate": {name: "PasswordLastUsed", transform: extractValueFn},
	},
	graph.Role: {
		"Id":         {name: "RoleId", transform: extractValueFn},
		"Name":       {name: "RoleName", transform: extractValueFn},
		"Arn":        {name: "Arn", transform: extractValueFn},
		"CreateDate": {name: "CreateDate", transform: extractValueFn},
		"Path":       {name: "Path", transform: extractValueFn},
	},
	graph.Group: {
		"Id":         {name: "GroupId", transform: extractValueFn},
		"Name":       {name: "GroupName", transform: extractValueFn},
		"Arn":        {name: "Arn", transform: extractValueFn},
		"CreateDate": {name: "CreateDate", transform: extractValueFn},
		"Path":       {name: "Path", transform: extractValueFn},
	},
	graph.Policy: {
		"Id":           {name: "PolicyId", transform: extractValueFn},
		"Name":         {name: "PolicyName", transform: extractValueFn},
		"Arn":          {name: "Arn", transform: extractValueFn},
		"CreateDate":   {name: "CreateDate", transform: extractValueFn},
		"UpdateDate":   {name: "UpdateDate", transform: extractValueFn},
		"Description":  {name: "Description", transform: extractValueFn},
		"IsAttachable": {name: "IsAttachable", transform: extractValueFn},
		"Path":         {name: "Path", transform: extractValueFn},
	},
}
