/* Copyright 2017 WALLIX

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// DO NOT EDIT
// This file was automatically generated with go generate
package properties

const (
	Actions                   = "Actions"
	ActionsEnabled            = "ActionsEnabled"
	AdjustmentType            = "AdjustmentType"
	Affinity                  = "Affinity"
	AlarmNames                = "AlarmNames"
	AlarmActions              = "AlarmActions"
	ApproximateMessageCount   = "ApproximateMessageCount"
	Association               = "Association"
	Architecture              = "Architecture"
	Arn                       = "Arn"
	Attachable                = "Attachable"
	AutoUpgrade               = "AutoUpgrade"
	ScalingGroupName          = "ScalingGroupName"
	AvailabilityZone          = "AvailabilityZone"
	AvailabilityZones         = "AvailabilityZones"
	BackupRetentionPeriod     = "BackupRetentionPeriod"
	Bucket                    = "Bucket"
	CallerReference           = "CallerReference"
	CertificateAuthority      = "CertificateAuthority"
	Certificates              = "Certificates"
	Charset                   = "Charset"
	CheckHTTPCode             = "CheckHTTPCode"
	CheckInterval             = "CheckInterval"
	CheckPath                 = "CheckPath"
	CheckPort                 = "CheckPort"
	CheckProtocol             = "CheckProtocol"
	CheckTimeout              = "CheckTimeout"
	CIDR                      = "CIDR"
	CIDRv6                    = "CIDRv6"
	CipherSuite               = "CipherSuite"
	Class                     = "Class"
	Cluster                   = "Cluster"
	Comment                   = "Comment"
	Continent                 = "Continent"
	Cooldown                  = "Cooldown"
	CopyTagsToSnapshot        = "CopyTagsToSnapshot"
	Country                   = "Country"
	Created                   = "Created"
	DBSecurityGroups          = "DBSecurityGroups"
	DBSubnetGroup             = "DBSubnetGroup"
	Default                   = "Default"
	DefaultCooldown           = "DefaultCooldown"
	Delay                     = "Delay"
	Description               = "Description"
	DesiredCapacity           = "DesiredCapacity"
	Dimensions                = "Dimensions"
	Encrypted                 = "Encrypted"
	Endpoint                  = "Endpoint"
	Engine                    = "Engine"
	EngineVersion             = "EngineVersion"
	Failover                  = "Failover"
	Fingerprint               = "Fingerprint"
	GlobalID                  = "GlobalID"
	GranteeType               = "GranteeType"
	Grants                    = "Grants"
	Handler                   = "Handler"
	Hash                      = "Hash"
	HealthCheck               = "HealthCheck"
	HealthCheckType           = "HealthCheckType"
	HealthCheckGracePeriod    = "HealthCheckGracePeriod"
	HealthyThresholdCount     = "HealthyThresholdCount"
	Host                      = "Host"
	Hypervisor                = "Hypervisor"
	ID                        = "ID"
	Image                     = "Image"
	InboundRules              = "InboundRules"
	InlinePolicies            = "InlinePolicies"
	Instances                 = "Instances"
	InsufficientDataActions   = "InsufficientDataActions"
	IOPS                      = "IOPS"
	IPType                    = "IPType"
	Key                       = "Key"
	KeyPair                   = "KeyPair"
	LatestRestorableTime      = "LatestRestorableTime"
	Launched                  = "Launched"
	LaunchConfigurationName   = "LaunchConfigurationName"
	License                   = "License"
	Lifecycle                 = "Lifecycle"
	LoadBalancer              = "LoadBalancer"
	Location                  = "Location"
	Main                      = "Main"
	MaxSize                   = "MaxSize"
	Memory                    = "Memory"
	Messages                  = "Messages"
	MetricName                = "MetricName"
	MinSize                   = "MinSize"
	Modified                  = "Modified"
	MonitoringInterval        = "MonitoringInterval"
	MonitoringRole            = "MonitoringRole"
	MultiAZ                   = "MultiAZ"
	Name                      = "Name"
	Namespace                 = "Namespace"
	NewInstancesProtected     = "NewInstancesProtected"
	NetworkInterfaces         = "NetworkInterfaces"
	OKActions                 = "OKActions"
	OptionGroups              = "OptionGroups"
	OutboundRules             = "OutboundRules"
	Owner                     = "Owner"
	ParameterGroups           = "ParameterGroups"
	PasswordLastUsed          = "PasswordLastUsed"
	Path                      = "Path"
	PlacementGroup            = "PlacementGroup"
	Port                      = "Port"
	PortRange                 = "PortRange"
	PreferredBackupDate       = "PreferredBackupDate"
	PreferredMaintenanceDate  = "PreferredMaintenanceDate"
	Private                   = "Private"
	PrivateIP                 = "PrivateIP"
	Profile                   = "Profile"
	Progress                  = "Progress"
	Protocol                  = "Protocol"
	Public                    = "Public"
	PublicDNS                 = "PublicDNS"
	PublicIP                  = "PublicIP"
	RecordCount               = "RecordCount"
	Records                   = "Records"
	Region                    = "Region"
	Role                      = "Role"
	RootDevice                = "RootDevice"
	RootDeviceType            = "RootDeviceType"
	Routes                    = "Routes"
	Runtime                   = "Runtime"
	ScalingAdjustment         = "ScalingAdjustment"
	Scheme                    = "Scheme"
	SecondaryAvailabilityZone = "SecondaryAvailabilityZone"
	SecurityGroups            = "SecurityGroups"
	Set                       = "Set"
	Size                      = "Size"
	SpotInstanceRequestId     = "SpotInstanceRequestId"
	SpotPrice                 = "SpotPrice"
	State                     = "State"
	StateMessage              = "StateMessage"
	Storage                   = "Storage"
	StorageType               = "StorageType"
	Subnet                    = "Subnet"
	Subnets                   = "Subnets"
	Tags                      = "Tags"
	Timeout                   = "Timeout"
	Timezone                  = "Timezone"
	Topic                     = "Topic"
	TrafficPolicyInstance     = "TrafficPolicyInstance"
	TTL                       = "TTL"
	Type                      = "Type"
	UnhealthyThresholdCount   = "UnhealthyThresholdCount"
	Updated                   = "Updated"
	UserData                  = "UserData"
	Username                  = "Username"
	Value                     = "Value"
	Version                   = "Version"
	Virtualization            = "Virtualization"
	Volume                    = "Volume"
	Vpc                       = "Vpc"
	Vpcs                      = "Vpcs"
	Weight                    = "Weight"
	Zone                      = "Zone"
)
