package awsdoc

import (
	"bytes"
	"fmt"
)

func AwlessExamplesDoc(action, entity string) string {
	return exampleDoc(action + entity)
}

func exampleDoc(key string) string {
	examples, ok := cliExamplesDoc[key]
	if ok {
		var buf bytes.Buffer
		for i, ex := range examples {
			buf.WriteString(fmt.Sprintf("  %s", ex))
			if i != len(examples)-1 {
				buf.WriteByte('\n')
			}
		}
		return buf.String()
	}
	return ""
}

var cliExamplesDoc = map[string][]string{
	"attachalarm":           {},
	"attachcontainertask":   {},
	"attachelasticip":       {},
	"attachinstance":        {},
	"attachinstanceprofile": {},
	"attachinternetgateway": {},
	"attachpolicy": {
		"awless attach policy role=MyNewRole service=ec2 access=readonly",
		"awless attach policy user=jsmith service=s3 access=readonly",
	},
	"attachrole":             {},
	"attachroutetable":       {},
	"attachsecuritygroup":    {},
	"attachuser":             {},
	"attachvolume":           {},
	"authenticateregistry":   {},
	"checkdatabase":          {},
	"checkdistribution":      {},
	"checkinstance":          {},
	"checkloadbalancer":      {},
	"checknatgateway":        {},
	"checkscalinggroup":      {},
	"checksecuritygroup":     {},
	"checkvolume":            {},
	"copyimage":              {},
	"copysnapshot":           {},
	"createaccesskey":        {},
	"createalarm":            {},
	"createappscalingpolicy": {},
	"createappscalingtarget": {},
	"createbucket":           {},
	"createcontainercluster": {},
	"createdatabase":         {},
	"createdbsubnetgroup":    {},
	"createdistribution":     {},
	"createelasticip":        {},
	"createfunction":         {},
	"creategroup":            {},
	"createinstance": {
		"awless create instance name=redis type=t2.nano keypair=jsmith userdata=/home/jsmith/data.sh role=MyInfraReadOnlyRole",
		"awless create instance keypair=jsmith image=ami-6523hr2pr",
	},
	"createinstanceprofile":     {},
	"createinternetgateway":     {},
	"createkeypair":             {},
	"createlaunchconfiguration": {},
	"createlistener":            {},
	"createloadbalancer":        {},
	"createloginprofile":        {},
	"createnatgateway":          {},
	"createpolicy":              {},
	"createqueue":               {},
	"createrecord":              {},
	"createrepository":          {},
	"createrole":                {},
	"createroute":               {},
	"createroutetable":          {},
	"creates3object":            {},
	"createscalinggroup":        {},
	"createscalingpolicy":       {},
	"createsecuritygroup":       {},
	"createsnapshot":            {},
	"createstack":               {},
	"createsubnet":              {},
	"createsubscription":        {},
	"createtag":                 {},
	"createtargetgroup":         {},
	"createtopic":               {},
	"createuser":                {},
	"createvolume":              {},
	"createvpc":                 {},
	"createzone":                {},
	"deleteaccesskey":           {},
	"deletealarm":               {},
	"deleteappscalingpolicy":    {},
	"deleteappscalingtarget":    {},
	"deletebucket":              {},
	"deletecontainercluster":    {},
	"deletecontainertask":       {},
	"deletedatabase":            {},
	"deletedbsubnetgroup":       {},
	"deletedistribution":        {},
	"deleteelasticip":           {},
	"deletefunction":            {},
	"deletegroup":               {},
	"deleteimage":               {},
	"deleteinstance":            {},
	"deleteinstanceprofile":     {},
	"deleteinternetgateway":     {},
	"deletekeypair":             {},
	"deletelaunchconfiguration": {},
	"deletelistener":            {},
	"deleteloadbalancer":        {},
	"deleteloginprofile":        {},
	"deletenatgateway":          {},
	"deletepolicy":              {},
	"deletequeue":               {},
	"deleterecord":              {},
	"deleterepository":          {},
	"deleterole":                {},
	"deleteroute":               {},
	"deleteroutetable":          {},
	"deletes3object":            {},
	"deletescalinggroup":        {},
	"deletescalingpolicy":       {},
	"deletesecuritygroup":       {},
	"deletesnapshot":            {},
	"deletestack":               {},
	"deletesubnet":              {},
	"deletesubscription":        {},
	"deletetag":                 {},
	"deletetargetgroup":         {},
	"deletetopic":               {},
	"deleteuser":                {},
	"deletevolume":              {},
	"deletevpc":                 {},
	"deletezone":                {},
	"detachalarm":               {},
	"detachcontainertask":       {},
	"detachelasticip":           {},
	"detachinstance":            {},
	"detachinstanceprofile":     {},
	"detachinternetgateway":     {},
	"detachpolicy":              {},
	"detachrole":                {},
	"detachroutetable":          {},
	"detachsecuritygroup":       {},
	"detachuser":                {},
	"detachvolume":              {},
	"importimage":               {},
	"startalarm":                {},
	"startcontainertask":        {},
	"startinstance":             {},
	"stopalarm":                 {},
	"stopcontainertask":         {},
	"stopinstance":              {},
	"updatebucket":              {},
	"updatecontainertask":       {},
	"updatedistribution":        {},
	"updateinstance":            {},
	"updateloginprofile":        {},
	"updaterecord":              {},
	"updates3object":            {},
	"updatescalinggroup":        {},
	"updatesecuritygroup":       {},
	"updatestack":               {},
	"updatesubnet":              {},
	"updatetargetgroup":         {},
}
